
tasks:
  - name: "init eliza env"
    init: |
      nvm install v"node":"20.10.0"
      git fetch --tags
      git checkout $(git describe --tags --abbrev=0)
    command: pnpm install && pnpm run build
